Add generated pb2 files to mvn clean.
Fixes this compilation error (after running mvn clean):
TypeError: __new__() got an unexpected keyword argument 'file'

which is due to BEAM-3357.