[BEAM-6111] Fix flaky PortableTimersExecutionTest (#7171)
This is caused by executing the state completion request in GrpcStateService
asynchronously with the default threadpool. I think this wasn't intended because
whenCompleteAsync was used instead of whenComplete. The default thread pool in
the test is Flink's thread pool which doesn't take care to log exceptions.

https://github.com/apache/beam/blob/c526f6bf62a1d63c7181eb7252c134e42d5c8677/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/state/GrpcStateService.java#L82

With the current implementation the StateRequest will always be a completed
CompleteableFuture anyways, so there is no need to schedule asynchronously.

The following exception was thrown here:
https://github.com/apache/beam/blob/c526f6bf62a1d63c7181eb7252c134e42d5c8677/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/state/GrpcStateService.java#L85

```
java.lang.IllegalStateException: sendHeaders has already been called
```