Update google-api-services-storage to match libraries-bom (#29865)
```
cd /tmp; wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.28.0/libraries-bom-26.28.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom
```

Yields

```
[INFO] |  +- com.google.apis:google-api-services-storage:jar:v1-rev20231202-2.0.0:compile
```

Making the change accordingly, since this mismatch is causing some errors on RC validation: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1233/checks?check_run_id=19897484522


```
java.lang.NoClassDefFoundError: com/google/api/services/storage/model/Bucket$ObjectRetention
	at com.google.cloud.storage.JsonConversions.<init>(JsonConversions.java:120)
	at com.google.cloud.storage.JsonConversions.<clinit>(JsonConversions.java:89)
	at com.google.cloud.storage.Conversions.json(Conversions.java:33)
	at com.google.cloud.storage.StorageImpl.<clinit>(StorageImpl.java:109)
```