Bump distlib version
:sdks:python:test-suites:tox:py38:testPy38CloudCoverage fails with
```
ImportError: cannot import name 'enquote_executable' from
'distlib.scripts'
(/home/chuck.yang/beam/build/gradleenv/-1227304282/lib/python3.8/site-packages/distlib/scripts.py)
```
when I don't bump this version. It's odd because 0.3.1 should be enough
to solve the problem...