[BEAM-7376] Update tox version used by gradle
This enables the settings added in #8450, which were being silently
ignored.

Also limit google-cloud-datastore version, due to an incompatibility in
Python 3 that `pip check` catches:

```
ERROR: google-cloud-datastore 1.8.0 has requirement google-cloud-core<2.0dev,>=1.0.0, but you'll have google-cloud-core 0.29.1 which is incompatible.
```