Fix Cassandra read bug when user query has no where clause
It would be very useful to be able to pass a user-defined query to CassandraIO for purposes of column selection only.

However, the current method for query parsing assumes such query necessarily comes with a 'where' clause, leading to an invalid resulting statement when this is not true.

Example of the current behavior:

Input query: "select partition_col, other_col from keyspace.table"

Resulting invalid query: "select partition_col, other_col from keyspace.table AND token(partition_col) >= ? and token(partition_col) < ?"

Resulting error:
SyntaxException: [...] mismatched input 'AND' expecting EOF (..., other_col from keyspace.table [AND]...)

The proposed change fixes this by checking if the user given query contains a where clause, appending a "WHERE" to it when it doesn't, instead of a "AND".