[BEAM-7170] Fix exception when retrieving ExpansionServer port after closing
The ExpansionServer can throw the following exception after shutdown because the
port getter retrieves the port dynamically from the underlying service:

```
java.lang.IllegalStateException: Already terminated
	at org.apache.beam.vendor.grpc.v1p13p1.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.beam.vendor.grpc.v1p13p1.io.grpc.internal.ServerImpl.getPort(ServerImpl.java:174)
	at org.apache.beam.runners.core.construction.expansion.ExpansionServer.getPort(ExpansionServer.java:66)
```