Fix repeat in AfterWatermark.withLateFirings()
Previously, AfterWatermark.withLateFirings(subTrigger) would
fail to fully reset subTrigger if it fired due to onTimer, resulting
in exceptions of this form:

Exception: java.lang.IllegalStateException:
Shouldn't invokeElement on finished triggers.
    com.google.cloud.dataflow.sdk.util.ExecutableTrigger.invokeElement...

----Release Notes----

[]
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=107107998