Add missing equal signs to example in comment
Running the command as mentioned in the comment results in:

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --test-pipeline-options: expected one argument

I've confirmed via git grep that --test-pipeline-options requires an
equal sign.