[BEAM-10622] Prefix Gradle paths with a colon for user-facing output
When using the FlinkRunner with master, the job server needs to be build
first. Beam prints out instructions for that, e.g.

```
RuntimeError: /Users/max/Dev/beam/runners/flink/1.10/job-server/build/libs/beam-runners-flink-1.10-job-server-2.24.0-SNAPSHOT.jar not found. Please build the server with
  cd /Users/max/Dev/beam; ./gradlew runners:flink:1.10:job-server:shadowJar
```

Note that the gradle path printed is not valid because it misses a colon before
"runners".

Internally, the Gradle path is used to resolve the jar locally or from Maven
Central. Gradle paths always start with a colon. We should stick to that format
although we can also parse Gradle paths which do not start with a colon.

In order for the Gradle path printed to be valid, we should prefix Gradle path
with colon.