Provide more explicit error message when Coder inference fails
Before:

java.lang.IllegalStateException: Unable to infer a default Coder for Partition/ParMultiDo(Partition).out2 [PCollection]; either correct the root cause below or use setCoder() to specify one explicitly.
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:48)
	at com.google.cloud.dataflow.sdk.values.PCollection.getCoder(PCollection.java:137)
	at com.google.cloud.dataflow.sdk.testing.DataflowAssert.that(DataflowAssert.java:113)

<snip>

Caused by: com.google.cloud.dataflow.sdk.coders.CannotProvideCoderException: default coder not provided
	at com.google.cloud.dataflow.sdk.transforms.ParDo$BoundMulti.getDefaultOutputCoder(ParDo.java:978)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$BoundMulti.getDefaultOutputCoder(ParDo.java:1)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.inferCoderOrFail(TypedPValue.java:156)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:46)
	... 28 more

After:

java.lang.IllegalStateException: Unable to return a default Coder for Partition/ParMultiDo(Partition).out1 [PCollection]. Correct one of the following root causes:
  No Coder has been manually specified;  you may do so using .setCoder().
  Inferring a Coder from the CoderRegistry failed: Cannot provide a Coder for type variable V because the actual type is unknown due to erasure. If this error occurs for a side output of the producing ParDo, verify that the TupleTag for this output is constructed with proper type information (see TupleTag Javadoc) or explicitly set the Coder to use if this is not possible.
  Using the Coder from the input PTransform failed: Cannot provide a Coder for type variable V because the actual type is unknown due to erasure.
	at com.google.cloud.dataflow.sdk.values.TypedPValue.inferCoderOrFail(TypedPValue.java:187)
	at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:46)
	at com.google.cloud.dataflow.sdk.values.PCollection.getCoder(PCollection.java:137)
	at com.google.cloud.dataflow.sdk.testing.DataflowAssert.that(DataflowAssert.java:113)
	at com.google.cloud.dataflow.sdk.transforms.PartitionTest.testModPartition(PartitionTest.java:85)
<snip junit part of stack trace>

----Release Notes----
[]
-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=102603658